project:
  type: website

website:
  title: "All Things Bioinformatics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jaychung10010
      - icon: linkedin
        href: https://www.linkedin.com/in/jay-cy-chung/
format:
  html:
    theme: default
    css: styles.css
